---
title: Reliability of experimental force measurements
execute:
  eval: false
---

The analysis of this page corresponds to the sections 'Reliability and
robustness of experimental results'.

Specifically, the following steps were taken:

-   Quantify the maximum force measured from GL+PL to verify limited mechanical
    interaction with GM.
-   Compute the coefficient of variation of repeated SR measurements.
-   Analyse repeated QR trials to assess shifts in SEE force and MTC
    force-length behaviour over the experiment.
-   Analyse repeated SR trials to assess changes in isometric force over the
    experiment.
-   Quantify cycle-to-cycle and trial-to-trial variation in experimentally
    measured AMPO.

Custom functions used:

-   `hillmodel.force_eq(lmtc, gamma, muspar)`
    : Finds relative CE length such that SEE force equals the sum of CE and
    PEE force.
-   `stats.pdiff(value1, value2)`
    : Compute the percentage difference between two values.

```{python}
{{< include reliability-experiments.py >}}
```
